# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: release-botcommons-beta

on:
    push:
        branches:
            - beta

jobs:
    build:

        runs-on: ubuntu-18.04

        steps:
            -   uses: actions/checkout@v2.3.4
            -   name: Set up java
                uses: actions/setup-java@v1.4.3
                with:
                    java-version: 8
            -   name: Grant execute permission for gradlew
                run: chmod +x gradlew
            -   name: dependencies
                run: ./gradlew --no-daemon dependencies
            -   name: Build and Release with Gradle
                env:
                    USERNAME: ${{ secrets.M2_USER }}
                    PASSWORD: ${{ secrets.M2_PASS }}
                    VERSION_PREFIX: beta_
                run: ./gradlew --no-daemon publish -x test
